version: '2'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - postgres
    environment:
      API_URL: http://localhost:3000
  postgres:
    image: postgres:10.16
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

